package org.andengine.manager;

/**
 * Created by Lukas on 12.07.2017.
 */

public enum SceneType {
    SCENE_SPLASH,
    SCENE_MENU,
    SCENE_LOADING,
    SCENE_LEVELS,
    SCENE_HELP,
    SCENE_SHOP,
    SCENE_MULTI,
    SCENE_GAME,
    SCENE_WORLD0,
    SCENE_WORLD1,
    SCENE_WORLD2,
    SCENE_WORLD3,
    SCENE_WORLD4,
    SCENE_WORLD5,
    SCENE_WORLD6,
    SCENE_WORLD7,
    SCENE_WORLD8,
    SCENE_HIGHSCORE,
    SCENE_SKILLGAME,
    SCENE_SKILLMENU,
}
